
GlobalFunctions = {
	'SBEN': ('f', '_SBEN'),
	'SBPR': ('s', '_SBPR'),
	'SBTM': ('f', '_SBTM'),
	'SBRP': ('iff', '?SBRP'),
	'SMPR': ('i', '_SMPR'),

	'SRAD': ('f', 'setradius'),
	'STGT': ('o', 'settarget'), #object
	'SXYZ': ('fff', 'sxyz'),
	'TXYZ': ('fff', 'txyz'),
	'STXT': ('iss', 'settexture'), #TODO return bool
	'SFAF': ('f', 'setfinishedafter'),

	'SDMG': ('b', '_SDMG'),
	'SBNC': ('b', '_SBNC'),
	'SVIS': ('s', '_SVIS'),
	'SAUD': ('s', '_SAUD'),
	'STOU': ('f', '_STOU'),
	'DACC': ('v', '_DACC'),
	'AACC': ('s', '_AACC'),
	'DDEC': ('v', '_DDEC'),
	'SWAC': ('s', '_SWAC'),
	'SFIL': ('s', '_SFIL'),
	'SMMD': ('ff', '_SMMD'),
	'SPRI': ('f', '_SPRI'),
	'SUTR': ('s', '_SUTR'),
	'SSTR': ('b', '_SSTR'),
	'SACT': ('b', '_SACT'),
	'SLOP': ('b', '_SLOP'),
	'SHMA': ('f', '_SHMA'),
	'SHMR': ('f', '_SHMR'),
	'SXEY': ('f', '_SXEY'),
	'SMAS': ('f', '_SMAS'),
	'SVCL': ('s', '_SVCL'),
	'STYP': ('s', '_STYP'),
	'SCLR': ('ffff', '_SCLR'),
	'SSPR': ('b', '_SSPR'),
	'SUCD': ('b', '_SUCD'),
	'SUNM': ('b', '_SUNM'),
	'SUCL': ('b', '_SUCL'),
	'SUV0': ('b', '_SUV0'),
	'SUV1': ('b', '_SUV1'),
	'SUV2': ('b', '_SUV2'),
	'SUV3': ('b', '_SUV3'),
	'SSDM': ('b', '_SSDM'),
	'RXYZ': ('fff', '_RXYZ'),
	'SCSH': ('b', '_SCSH'),
	'M_SH': ('b', '_M_SH'),
	'SRMV': ('b', '_SRMV'),
	'SPSD': ('b', '_SPSD'),
	'STHC': ('b', '_STHC'),
	'SVBL': ('b', '_SVBL'),
	'SAFM': ('b', '_SAFM'),
	'SAFU': ('b', '_SAFU'),
	'SIQS': ('b', '_SIQS'),
	'SFCA': ('b', '_SFCA'),
	'SINS': ('b', '_SINS'),
	'ENEM': ('b', '_ENEM'),
	'SUEP': ('b', '_SUEP'),
	'SSMD': ('b', '_SSMD'),
	'SQSA': ('b', '_SQSA'),
	'STHR': ('b', '_STHR'),
	'CCML': ('v', '_CCML'),
	'SACO': ('f', '_SACO'),
	'SSTB': ('f', '_SSTB'),
	'SUTE': ('s', '_SUTE'),
	'SETF': ('f', 'setfloat'),

	'SAMV': ('b', '_SAMV'),
	'SART': ('b', '_SART'),
	'IGNB': ('b', '_IGNB'),
	'IGNS': ('b', '_IGNS'),
	'IGNF': ('b', '_IGNF'),

	'SPOS': ('fff', '_SPOS'),
	'SDIR': ('fff', '_SDIR'),
	'SEGY': ('f', '_SEGY'),
	'SCTM': ('f', '_SCTM'),
	'RTMD': ('f', '_RTMD'),
	'SPOP': ('i', '_SPOP'),
	'SAUE': ('f', '_SAUE'),
	'SMCG': ('i', '_SMCG'),
	'SCRG': ('i', '_SCRG'),
	'SRTI': ('f', '_SRTI'),
	'SHMC': ('fff', '_SHMC'),
	'SRAC': ('f', '_SRAC'),

	'SATT': ('fff', '?SATT'),
	'SARM': ('si', '?SARM'),
	'SDTP': ('s', '?SDTP'),
	'SDBR': ('s', '?SDBR'),
	'ADBR': ('sfffffff', '?ADBR')
}
