Classes = {
	'n3dnode': {
		'QXYZ': ('ffff', '_QXYZ'),
		'SBLB': ('b', '_SBLB'),
		'SHDT': ('b', '_SHDT'),
		'SLVW': ('b', '_SLVW'),
		'SMLD': ('f', '_SMLD'),
		'SVWS': ('b', '_SVWS'),
		'RXYZ': ('fff', 'rotate_xyz'),
		'SACT': ('b', '_SACT'),
		'SFAF': ('f', 'setfinishedafter'),
		'SSPR': ('b', '_SSPR'),
		'SXYZ': ('fff', 'scale_xyz'),
		'TXYZ': ('fff', 'translate_xyz'),
	},
	'nflipflop': {
		'SRPT': ('s', 'setreptype'),
		'SCHN': ('s', 'setchannel'),
		'SSCL': ('f', 'setscale'),
		'AKEY': ('fs', 'add_key'),
	},
	'nmeshipol': {
		'SKEY': ('ifs', 'setkey'),
		'BKEY': ('i', 'beginkeys'),
		'EKEY': ('v', 'endkeys'),
		'SCHN': ('s', 'setchannel'),
		'SRDO': ('b', '_SRDO'),
		'SRPT': ('s', 'setreptype'),
		'SSCL': ('f', 'setscale'),
		'SUCD': ('b', '_SUCD'),
		'SUCL': ('b', '_SUCL'),
	},
	'nchnsplitter': {
		'BKEY': ('i', 'beginkeys'),
		'EKEY': ('v', 'endkeys'),
		'SCHN': ('s', 'setchannel'),
		'SKEY': ('ifs', 'setkey'),
		'SRPT': ('s', 'setreptype'),
		'SSCL': ('f', 'setscale'),
	},
	'nlinknode': {
		'STGT': ('o', 'settarget'),
	},
	'nmeshnode': {
		'SKEY': ('iffffff', 'setkey'),
		'SFLN': ('s', 'setfilename'),
		'SRDO': ('b', '_SRDO'),
		'SCSD': ('b', '_SCSD'),
	},
	'nparticlesystem': {
		'SLFT': ('f', 'setlifetime'),
		'SFRQ': ('f', 'setfreq'),
		'SSPD': ('f', 'setspeed'),
		'SACC': ('fff', 'setaccel'),
		'SICN': ('f', 'setinnercone'),
		'SOCN': ('f', 'setoutercone'),
		'SSPN': ('f', 'setspin'),
		'SSPA': ('f', 'setspinaccel'),
		'SEMT': ('s', 'setemmiter'),
	},
	'njointanim': {
		'BGJN': ('i', 'beginjoints'),
		'EDJN': ('v', 'endjoints'),
		'ADJN': ('isifffffff', 'addjoint'),
		'BGST': ('i', 'beginstates'),
		'ADST': ('is', 'addstate'),
		'BGSA': ('ii', 'beginstateanims'),
		'ADSA': ('iis', 'addstateanim'),
		'EDSA': ('i', 'endstateanims'),
		'EDST': ('v', 'endstates'),
		'BGHP': ('i', 'beginhardpoints'),
		'ADHP': ('iis', 'addhardpoint'),
		'EDHP': ('v', 'endhardpoints'),
	},
	'nipol': {
		'SK1F': ('iff', 'setkeys1f'),
		'SK2F': ('ifff', 'setkeys2f'),
		'SK3F': ('iffff', 'setkeys3f'),
		'SK4F': ('ifffff', 'setkeys4f'),
		'SRPT': ('s', 'setreptype'),
		'SCHN': ('s', 'setchannel'),
		'CNCT': ('s', 'connect'),
		'SSCL': ('f', 'setscale'),
		'BGKS': ('ii', 'beginkeys'),
		'ENKS': ('v', 'endkeys'),
		'SIPT': ('s', '_SIPT'),
	},
	'nchnmodulator': {
		'BGIN': ('i', 'begin'),
		'SET_': ('iss', 'set'),
		'END_': ('v', 'end'),
	},
	'nhousemenu': {
		'SMRD': ('f', '_SMRD'),
		'STAD': ('f', '_STAD'),
		'SISP': ('f', '_SISP'),
		'SIDS': ('f', '_SIDS'),
	},
	'ncloud': {
		'BCDS': ('if', '_BCDS'),
		'SLNF': ('f', '_SLNF'),
		'ECDS': ('v', 'enableclouds'),
	},
	'nmissileengine3': {
		'SIDL': ('f', '_SIDL'),
		'SGVF': ('f', '_SGVF'),
		'SMXS': ('f', '_SMXS'),
		'SAGL': ('f', '_SAGL'),
	},
	'nmeshcluster2': {
		'SSMS': ('s', '_SSMS'),
		'SCTS': ('b', '_SCTS'),
		'SRTJ': ('s', '_SRTJ'),
		'SRDO': ('b', '_SRDO'),
	},
	'ncurvearraynode': { #nipol
		'BGCN': ('i', 'beginconnects'),
		'EDCN': ('v', 'endconnects'),
		'SCHN': ('s', 'setchannel'),
		'SRPT': ('s', 'setreptype'),
		'SSCL': ('f', 'setscale'),
		'SFLN': ('s', 'setfilename'),
		'EDBD': ('v', '_EDBD'),
		'SBC2': ('iss', '_SBC2'),
		'BGBD': ('is', '_BGBD'),
		'BGCB': ('i', '_BGCB'),
		'SCBD': ('iss', '_SCBD'),
		'EBCB': ('v', '_EBCB'),
		'SCC2': ('iss', '_SCBD'),
	},
	'nweighttree': {
		'ANOD': ('sss', 'addnode'),
		'ALEF': ('s', 'addleaf'),
	},
	'ncharacternode': { # njointanim, nchsplitter, nmeshnode
		'EDSA': ('i', 'endstateanims'),
		'BGHP': ('i', 'beginhardpoints'),
		'BGSA': ('ii', 'beginstateanims'),
		'BGJN': ('i', 'beginjoints'),
		'SSKM': ('s', '_SSKM'),
		'SRPT': ('s', 'setreptype'),
		'EDHP': ('v', 'endhardpoints'),
		'ADSA': ('iis', 'addstateanim'),
		'SRDO': ('b', '_SRDO'),
		'EDJN': ('v', 'endjoints'),
		'ADJN': ('isifffffff', 'addjoint'),
		'SCHN': ('s', 'setchannel'),
		'SSCL': ('f', 'setscale'),
		'ADHP': ('iis', 'addhardpoint'),
		'SSTC': ('s', '_SSTC'),
		'EDST': ('v', 'endstates'),
		'SANF': ('s', '_SANF'),
		'BGST': ('i', 'beginstates'),
		'SCSS': ('b', '_SCSS'),
		'ADST': ('is', 'addstate'),
	},
	'nanimsequence': {
		'ADTK': ('ffff', '_ADTK'),
		'ADQK': ('fffff', '_ADQK'),
		'STIT': ('i', '?STIT'),
		'SVRL': ('b', '_SVRL'),
		'ADVK': ('fs', '_ADVK'),
		'ADAK': ('fs', '_ADAK'),
		'ADRK': ('ffff', '_ADRK'),
	},
	'ntrailrender': {
		'SKEY': ('iffffff', 'setkey'),
		'BKEY': ('i', 'beginkeys'),
		'EKEY': ('v', 'endkeys'),
		'SCHN': ('s', 'setchannel'),
		'SEMT': ('s', 'setemmiter'),
		'SRPT': ('s', 'setreptype'),
		'SSCL': ('f', 'setscale'),
		'SSPA': ('f', 'setspinaccel'),
		'SSPN': ('f', 'setspin'),
		'SSTR': ('b', '_SSTR'),
	},
	'nspriterender': {
		'SRPT': ('s', 'setreptype'),
		'SCHN': ('s', 'setchannel'),
		'SSCL': ('f', 'setscale'),
		'SSPN': ('f', 'setspin'),
		'SSPA': ('f', 'setspinaccel'),
		'SEMT': ('s', 'setemmiter'),
		'BKEY': ('i', 'beginkeys'),
		'SKEY': ('iffffff', 'setkey'),
		'EKEY': ('v', 'endkeys'),
		'SSTR': ('b', '_SSTR'),
	},
	'nmeshemitter': { # nparticlesystem
		'SACC': ('fff', 'setaccel'),
		'SOCN': ('f', 'setoutercone'),
		'SCHN': ('s', 'setchannel'),
		'SRPT': ('s', 'setreptype'),
		'SICN': ('f', 'setinnercone'),
		'SSCL': ('f', 'setscale'),
		'SSPD': ('f', 'setspeed'),
		'STMS': ('fff', '_STMS'),
		'SMSN': ('s', '_SMSN'),
		'SFRQ': ('f', 'setfreq'),
		'SLFT': ('f', 'setlifetime'),
	},
	'nshadernode': {
		'SMMF': ('s', 'set_min_max_filter'),
		'SEMV': ('fff', '_SEMV'),
		'SPOP': ('i', '_SPOP'),
		'SADR': ('s', 'set_ADR'),
		'SABL': ('s', 'set_alpha_blending'),
		'SZFC': ('s', 'set_ZFC'),
		'SCMD': ('s', 'set_CMD'),
		'SCLM': ('s', 'set_CLM'),
		'SAFC': ('s', 'set_AFC'),
		'SAOP': ('is', 'set_AOP'),
		'SDIF': ('ffff', 'set_diffuse_color'),
		'SAMB': ('ffff', 'set_ambient_color'),
		'SCOT': ('iiiii', '_SCOT'),
		'SLEN': ('b', 'set_LEN'),
		'SAEN': ('b', 'set_AEN'),
		'SZEN': ('b', 'set_ZEN'),
		'SFEN': ('b', 'set_FEN'),
		'SATE': ('b', 'set_ATE'),
		'SENT': ('b', '_SENT'),
		'SMLB': ('i', '_SMLB'),
		'SNST': ('i', '_SNST'),
		'BGTU': ('i', '_BGTU'),
		'SARF': ('f', '_SARF'),
		'SRPR': ('i', '_SRPR'),
		'EDTU': ('v', 'enable_DTU'),
		'STCS': ('s', 'set_TCS'),
		'TXYZ': ('fff', 'translate_xyz'),
		'RXYZ': ('fff', 'rotate_xyz'),
		'SXYZ': ('fff', 'scale_xyz'),
	},
	'nairplane3': {
		'SATM': ('f', '_SATM'),
		'SDTM': ('f', '_SDTM'),
		'SISP': ('f', '_SISP'),
		'SMPI': ('f', '_SMPI'),	
		'SMPT': ('f', '_SMPT'),
		'SMRL': ('f', '_SMRL'),
		'SMRT': ('f', '_SMRT'),
		'SXSP': ('f', '_SXSP'),
		'SXYR': ('f', '_SXYR'),
		'SYAT': ('f', '_SYAT'),
	},
	'nbuildartefact': {
		'SBEN': ('f', '_SBEN'),
		'SBPR': ('s', '_SBPR'),
		'SBTM': ('f', '_SBTM'),
		'SBRP': ('iff', '?SBRP'),
		'SMPR': ('i', '_SMPR'),
		'SSID': ('i', '_SSID'),
	},
	###################
	'nairship3': {
		'SDTM': ('f', 'SDTM'),
		'SMRL': ('f', 'SMRL'),
		'SXSP': ('f', 'SXSP'),
		'SXVS': ('f', 'SXVS'),
		'SYAT': ('f', 'SYAT'),
		'SVAT': ('f', 'SVAT'),
		'SXYR': ('f', 'SXYR'),
		'SMRT': ('f', 'SMRT'),
		'SATM': ('f', 'SATM'),
	},
	'nartefactstorage': {
		'SRAD': ('f', 'SRAD'),
		'SEGY': ('i', 'SEGY'),
		'SRAC': ('i', 'SRAC'),
		'SACO': ('i', 'SACO'),
		'SINS': ('b', 'SINS'),
		'SIQS': ('b', 'SIQS'),
		'SUEP': ('b', 'SUEP'),
		'SLDM': ('i', 'SLDM'),
		'ENEM': ('b', 'ENEM'),
		'SVCL': ('s', 'SVCL'),
		'SLFT': ('i', 'SLFT'),
		'SDIR': ('iii', 'set_direction'),
		'SXEY': ('f', 'SXEY'),
		'CCML': ('v', 'CCML'),
		'SRMV': ('b', 'SRMV'),
		'SAUD': ('i', 'SAUD'),
		'SPSD': ('b', 'SPSD'),
		'SSPD': ('iii', 'SSPD'),
		'SFCA': ('b', 'SFCA'),
		'SMAS': ('f', 'SMAS'),
		'SAFM': ('b', 'SAFM'),
		'SQSA': ('b', 'SQSA'),
		'SAUE': ('f', 'SAUE'),
		'SPOP': ('i', 'SPOP'),
		'SPOS': ('iii', 'set_position'),
		'SHMR': ('f', 'SHMR'),
		'SSBS': ('iff', 'SSBS'),
		'SBDC': ('s', 'SBDC'),
		'SSMD': ('b', 'SSMD'),
		'SAFU': ('b', 'SAFU'),
		'SHMC': ('iii', 'SHMC'),
		'SMCG': ('i', 'SMCG'),
		'SHMA': ('f', 'SHMA'),
		'SARM': ('si', 'SARM'),
		'SVBL': ('b', 'SVBL'),
		'SUTR': ('s', 'SUTR'),
		'SCPY': ('i', 'SCPY'),
		'STHC': ('b', 'STHC'),
		'SCTM': ('i', 'SCTM'),
		'M_SH': ('b', 'M_SH'),
		'SUTE': ('s', 'SUTE'),
		'SRTI': ('i', 'SRTI'),
		'SCRG': ('i', 'SCRG'),
		'SSTB': ('i', 'SSTB'),
		'STHR': ('b', 'STHR'),
	},
	'nartefacttransformer': {
		'SRAD': ('f', 'SRAD'),
		'SEGY': ('f', 'SEGY'),
		'SRAC': ('i', 'SRAC'),
		'SACO': ('i', 'SACO'),
		'SINS': ('b', 'SINS'),
		'SIQS': ('b', 'SIQS'),
		'SUEP': ('b', 'SUEP'),
		'ENEM': ('b', 'ENEM'),
		'SVCL': ('s', 'SVCL'),
		'SLFT': ('i', 'SLFT'),
		'SDAN': ('b', 'SDAN'),
		'SDIR': ('iii', 'set_direction'),
		'SXEY': ('f', 'SXEY'),
		'CCML': ('v', 'CCML'),
		'SSFX': ('s', 'SSFX'),
		'SRMV': ('b', 'SRMV'),
		'SAUD': ('i', 'SAUD'),
		'SPSD': ('b', 'SPSD'),
		'SSPD': ('iii', 'SSPD'),
		'SFCA': ('b', 'SFCA'),
		'SMAS': ('f', 'SMAS'),
		'SAFM': ('b', 'SAFM'),
		'SQSA': ('b', 'SQSA'),
		'SAUE': ('f', 'SAUE'),
		'SPOP': ('i', 'SPOP'),
		'SPOS': ('iii', 'set_position'),
		'SHMR': ('f', 'SHMR'),
		'SSBS': ('fff', 'SSBS'),
		'SBDC': ('s', 'SBDC'),
		'SSMD': ('b', 'SSMD'),
		'SAFU': ('b', 'SAFU'),
		'SHMC': ('iff', 'SHMC'),
		'SMCG': ('i', 'SMCG'),
		'SHMA': ('f', 'SHMA'),
		'SVBL': ('b', 'SVBL'),
		'SUTR': ('s', 'SUTR'),
		'SCTM': ('i', 'SCTM'),
		'STHC': ('b', 'STHC'),
		'SARM': ('sf', 'SARM'),
		'M_SH': ('b', 'M_SH'),
		'SUTE': ('s', 'SUTE'),
		'SRTI': ('i', 'SRTI'),
		'SCRG': ('i', 'SCRG'),
		'SSTB': ('i', 'SSTB'),
		'STHR': ('b', 'STHR'),
	},
	'nattack': {
		'SSTA': ('f', 'SSTA'),
		'SWRD': ('f', 'SWRD'),
		'SRAT': ('b', 'SRAT'),
		'SATA': ('b', 'SATA'),
		'SSTD': ('f', 'SSTD'),
		'SFTD': ('i', 'SFTD'),
		'SFTA': ('f', 'SFTA'),
	},
	'naudio': {
		'SAUD': ('s', 'SAUD'),
	},
	'navoidcollision': {
		'SKKZ': ('b', 'SKKZ'),
		'SISO': ('b', 'SISO'),
		'SAVR': ('f', 'SAVR'),
		'SSMR': ('f', 'SSMR'),
	},
	'nbombard': {
		'SRAT': ('b', 'SRAT'),
		'SABR': ('f', 'SABR'),
		'SFTD': ('i', 'SFTD'),
		'SFTA': ('f', 'SFTA'),
	},
	'nbomber': {
		'SRAD': ('f', 'SRAD'),
		'SVMG': ('b', 'SVMG'),
		'SEGY': ('i', 'SEGY'),
		'SRAC': ('f', 'SRAC'),
		'SVGR': ('b', 'SVGR'),
		'SACO': ('f', 'SACO'),
		'SINS': ('b', 'SINS'),
		'SIQS': ('b', 'SIQS'),
		'SUEP': ('b', 'SUEP'),
		'SLFT': ('i', 'SLFT'),
		'SVCL': ('s', 'SVCL'),
		'ENEM': ('b', 'ENEM'),
		'SSBA': ('b', 'SSBA'),
		'ASTC': ('s', 'ASTC'),
		'SDIR': ('iii', 'set_direction'),
		'SXEY': ('f', 'SXEY'),
		'CCML': ('v', 'CCML'),
		'SRMV': ('b', 'SRMV'),
		'SAUD': ('i', 'SAUD'),
		'SPSD': ('b', 'SPSD'),
		'SSPD': ('iii', 'SSPD'),
		'SFCA': ('b', 'SFCA'),
		'SMAS': ('f', 'SMAS'),
		'SAFM': ('b', 'SAFM'),
		'SQSA': ('b', 'SQSA'),
		'SAUE': ('i', 'SAUE'),
		'SPOP': ('i', 'SPOP'),
		'CSTC': ('v', 'CSTC'),
		'SPOS': ('iii', 'set_position'),
		'SSTB': ('f', 'SSTB'),
		'SAFU': ('b', 'SAFU'),
		'SMCG': ('i', 'SMCG'),
		'SVBL': ('b', 'SVBL'),
		'SISG': ('b', 'SISG'),
		'SCTM': ('i', 'SCTM'),
		'SUTR': ('s', 'SUTR'),
		'STHC': ('b', 'STHC'),
		'SARM': ('si', 'SARM'),
		'SCPP': ('i', 'SCPP'),
		'M_SH': ('b', 'M_SH'),
		'SSTK': ('s', 'SSTK'),
		'SRTI': ('f', 'SRTI'),
		'SCRG': ('i', 'SCRG'),
		'SRPO': ('ifi', 'SRPO'),
		'SLPP': ('i', 'SLPP'),
		'STHR': ('b', 'STHR'),
		'SSTD': ('f', 'SSTD'),
	},
	'nbuildflak': {
		'SSID': ('i', 'SSID'),
		'SBTM': ('i', 'SBTM'),
		'SMPR': ('i', 'SMPR'),
		'SBPR': ('s', 'SBPR'),
		'SBEN': ('i', 'SBEN'),
		'SBRP': ('ifi', 'SBRP'),
	},
	'nbuildtradeartefact': {
		'SSID': ('i', 'SSID'),
		'SBTM': ('i', 'SBTM'),
		'SMPR': ('i', 'SMPR'),
		'SBPR': ('s', 'SBPR'),
		'SBEN': ('f', 'SBEN'),
		'SBRP': ('fff', 'SBRP'),
	},
	'nbuildvehicle': {
		'SSID': ('i', 'SSID'),
		'SBTM': ('f', 'SBTM'),
		'SICM': ('s', 'SICM'),
		'SMPR': ('i', 'SMPR'),
		'SBPR': ('s', 'SBPR'),
		'SBEN': ('i', 'SBEN'),
		'SBRP': ('iii', 'SBRP'),
	},
	'ncharaudio': {
		'STUR': ('b', 'STUR'),
		'SFDE': ('f', 'SFDE'),
		'SFDB': ('f', 'SFDB'),
		'SDEB': ('f', 'SDEB'),
		'SAUD': ('s', 'SAUD'),
		'SDEL': ('f', 'SDEL'),
	},
	'nchnreader': {
		'ECNC': ('v', 'ECNC'),
		'BCNC': ('i', 'BCNC'),
		'SCNC': ('iss', 'SCNC'),
	},
	'ncinedummy': {
		'SRAD': ('i', 'SRAD'),
		'SEGY': ('i', 'SEGY'),
		'SRAC': ('i', 'SRAC'),
		'SACO': ('i', 'SACO'),
		'SINS': ('b', 'SINS'),
		'SIQS': ('b', 'SIQS'),
		'SUEP': ('b', 'SUEP'),
		'ENEM': ('b', 'ENEM'),
		'SVCL': ('s', 'SVCL'),
		'SLFT': ('i', 'SLFT'),
		'SDIR': ('iii', 'set_direction'),
		'SXEY': ('i', 'SXEY'),
		'CCML': ('v', 'CCML'),
		'SAUE': ('i', 'SAUE'),
		'SAUD': ('i', 'SAUD'),
		'SPSD': ('b', 'SPSD'),
		'SSPD': ('iii', 'SSPD'),
		'SFCA': ('b', 'SFCA'),
		'SMAS': ('i', 'SMAS'),
		'SAFM': ('b', 'SAFM'),
		'SQSA': ('b', 'SQSA'),
		'SRMV': ('b', 'SRMV'),
		'SPOP': ('i', 'SPOP'),
		'SPOS': ('iii', 'set_position'),
		'SAFU': ('b', 'SAFU'),
		'SMCG': ('i', 'SMCG'),
		'SVBL': ('b', 'SVBL'),
		'SUTR': ('s', 'SUTR'),
		'SCTM': ('i', 'SCTM'),
		'STHC': ('b', 'STHC'),
		'M_SH': ('b', 'M_SH'),
		'SRTI': ('i', 'SRTI'),
		'SCRG': ('i', 'SCRG'),
		'SSTB': ('i', 'SSTB'),
		'STHR': ('b', 'STHR'),
	},
	'nclouddesc': {
		'SWND': ('ii', 'SWND'),
		'SCOM': ('iii', 'SCOM'),
		'SCQU': ('iii', 'SCQU'),
		'SLAL': ('i', 'SLAL'),
		'SFCL': ('iffi', 'SFCL'),
		'SCOS': ('i', 'SCOS'),
		'SCOP': ('f', 'SCOP'),
		'SCSI': ('fff', 'SCSI'),
		'SFMO': ('f', 'SFMO'),
	},
	'ncloudrender': {
		'SRAD': ('f', 'SRAD'),
		'SEMM': ('iiii', 'SEMM'),
		'SRPT': ('s', 'SRPT'),
		'SMSN': ('s', 'SMSN'),
		'SAMB': ('iiii', 'SAMB'),
		'SDIF': ('iiii', 'SDIF'),
		'SABS': ('iiii', 'SABS'),
		'SALP': ('f', 'SALP'),
		'SSCL': ('f', 'SSCL'),
		'SCHN': ('s', 'SCHN'),
	},
	'nclouds': {
		'SLNF': ('f', 'SLNF'),
		'BCDS': ('if', 'BCDS'),
		'ECDS': ('v', 'ECDS'),
	},
	'ncollcheck2': {
		'SRAD': ('i', 'SRAD'),
		'SCLC': ('s', 'SCLC'),
		'SSHP': ('s', 'SSHP'),
	},
	'ncollectartefact': {
		'SCDI': ('f', 'SCDI'),
	},
	'ncollectore': {
		'SRAT': ('b', 'SRAT'),
		'SFTD': ('i', 'SFTD'),
		'SCPS': ('f', 'SCPS'),
		'SFTA': ('f', 'SFTA'),
	},
	'ncollhandle2': {
		'SBNC': ('b', 'SBNC'),
		'SCLF': ('s', 'SCLF'),
		'SDMG': ('b', 'SDMG'),
	},
	'nconsumption': {
		'SCMP': ('f', 'SCMP'),
	},
	'ncontainer': {
		'SRAD': ('i', 'SRAD'),
		'SEGY': ('i', 'SEGY'),
		'SRAC': ('i', 'SRAC'),
		'SACO': ('i', 'SACO'),
		'SINS': ('b', 'SINS'),
		'SIQS': ('b', 'SIQS'),
		'SUEP': ('b', 'SUEP'),
		'ENEM': ('b', 'ENEM'),
		'SVCL': ('s', 'SVCL'),
		'SLFT': ('i', 'SLFT'),
		'SDIR': ('iii', 'set_direction'),
		'SXEY': ('i', 'SXEY'),
		'CCML': ('v', 'CCML'),
		'SAUE': ('i', 'SAUE'),
		'SAUD': ('i', 'SAUD'),
		'SPSD': ('b', 'SPSD'),
		'SSPD': ('iii', 'SSPD'),
		'SFCA': ('b', 'SFCA'),
		'SMAS': ('i', 'SMAS'),
		'SAFM': ('b', 'SAFM'),
		'SQSA': ('b', 'SQSA'),
		'SRMV': ('b', 'SRMV'),
		'SPOP': ('i', 'SPOP'),
		'SPOS': ('iii', 'set_position'),
		'SAFU': ('b', 'SAFU'),
		'SMCG': ('i', 'SMCG'),
		'SVBL': ('b', 'SVBL'),
		'SUTR': ('s', 'SUTR'),
		'SCTM': ('i', 'SCTM'),
		'STHC': ('b', 'STHC'),
		'SARM': ('si', 'SARM'),
		'M_SH': ('b', 'M_SH'),
		'SRTI': ('i', 'SRTI'),
		'SCRG': ('i', 'SCRG'),
		'SSTB': ('i', 'SSTB'),
		'STHR': ('b', 'STHR'),
	},
	'ncritter2': {
		'SRAD': ('f', 'SRAD'),
		'SVMG': ('b', 'SVMG'),
		'SEGY': ('i', 'SEGY'),
		'SRAC': ('i', 'SRAC'),
		'SVGR': ('b', 'SVGR'),
		'SACO': ('i', 'SACO'),
		'SINS': ('b', 'SINS'),
		'SIQS': ('b', 'SIQS'),
		'SUEP': ('b', 'SUEP'),
		'SLFT': ('i', 'SLFT'),
		'SVCL': ('s', 'SVCL'),
		'ENEM': ('b', 'ENEM'),
		'SSBA': ('b', 'SSBA'),
		'ASTC': ('s', 'ASTC'),
		'SDIR': ('iii', 'set_direction'),
		'SXEY': ('i', 'SXEY'),
		'CCML': ('v', 'CCML'),
		'SRMV': ('b', 'SRMV'),
		'SAUD': ('i', 'SAUD'),
		'SPSD': ('b', 'SPSD'),
		'SSPD': ('iii', 'SSPD'),
		'SFCA': ('b', 'SFCA'),
		'SMAS': ('f', 'SMAS'),
		'SAFM': ('b', 'SAFM'),
		'SQSA': ('b', 'SQSA'),
		'SAUE': ('i', 'SAUE'),
		'SPOP': ('i', 'SPOP'),
		'CSTC': ('v', 'CSTC'),
		'SPOS': ('iii', 'set_position'),
		'SAFU': ('b', 'SAFU'),
		'SMCG': ('i', 'SMCG'),
		'SVBL': ('b', 'SVBL'),
		'SISG': ('b', 'SISG'),
		'SCTM': ('i', 'SCTM'),
		'SUTR': ('s', 'SUTR'),
		'STHC': ('b', 'STHC'),
		'SARM': ('si', 'SARM'),
		'SCPP': ('i', 'SCPP'),
		'M_SH': ('b', 'M_SH'),
		'SSTK': ('s', 'SSTK'),
		'SRTI': ('i', 'SRTI'),
		'SCRG': ('i', 'SCRG'),
		'SSTB': ('i', 'SSTB'),
		'SLPP': ('i', 'SLPP'),
		'STHR': ('b', 'STHR'),
		'SSTD': ('f', 'SSTD'),
	},
	'ncrittercollhandle': {
		'SBNC': ('b', 'SBNC'),
		'AVCL': ('s', 'AVCL'),
		'SDMG': ('b', 'SDMG'),
		'SCAC': ('s', 'SCAC'),
	},
	'ncritterdamage': {
		'SDRA': ('f', 'SDRA'),
	},
	'ncritterengine2': {
		'SMXS': ('f', 'SMXS'),
	},
	'nenergycollector': {
		'SCDN': ('f', 'SCDN'),
	},
	'nenv': {
		'SETF': ('f', 'SETF'),
	},
	'nexplosion': {
		'SSDM': ('b', 'SSDM'),
		'SDBR': ('s', 'SDBR'),
		'SECL': ('s', 'SECL'),
		'SXPR': ('i', 'SXPR'),
		'ADBR': ('siiiffff', 'ADBR'),
		'SXPE': ('i', 'SXPE'),
		'SDTP': ('s', 'SDTP'),
	},
	'nfactory': {
		'SRAD': ('f', 'SRAD'),
		'SEGY': ('i', 'SEGY'),
		'SRAC': ('i', 'SRAC'),
		'SACO': ('i', 'SACO'),
		'SINS': ('b', 'SINS'),
		'SIQS': ('b', 'SIQS'),
		'SUEP': ('b', 'SUEP'),
		'ENEM': ('b', 'ENEM'),
		'SVCL': ('s', 'SVCL'),
		'SLFT': ('i', 'SLFT'),
		'SDIR': ('iii', 'set_direction'),
		'SXEY': ('f', 'SXEY'),
		'CCML': ('v', 'CCML'),
		'SAUE': ('i', 'SAUE'),
		'SAUD': ('i', 'SAUD'),
		'SPSD': ('b', 'SPSD'),
		'SSPD': ('iii', 'SSPD'),
		'SFCA': ('b', 'SFCA'),
		'SMAS': ('f', 'SMAS'),
		'SAFM': ('b', 'SAFM'),
		'SQSA': ('b', 'SQSA'),
		'SRMV': ('b', 'SRMV'),
		'SPOP': ('i', 'SPOP'),
		'SPOS': ('iii', 'set_position'),
		'SHMR': ('f', 'SHMR'),
		'SSTB': ('i', 'SSTB'),
		'SBDC': ('s', 'SBDC'),
		'SSMD': ('b', 'SSMD'),
		'SAFU': ('b', 'SAFU'),
		'SHMC': ('iii', 'SHMC'),
		'SMCG': ('i', 'SMCG'),
		'SHMA': ('f', 'SHMA'),
		'SVBL': ('b', 'SVBL'),
		'SUTR': ('s', 'SUTR'),
		'SCTM': ('i', 'SCTM'),
		'STHC': ('b', 'STHC'),
		'SARM': ('si', 'SARM'),
		'M_SH': ('b', 'M_SH'),
		'SUTE': ('s', 'SUTE'),
		'SRTI': ('i', 'SRTI'),
		'SCRG': ('i', 'SCRG'),
		'SPCT': ('ii', 'SPCT'),
		'STHR': ('b', 'STHR'),
		'SFBD': ('b', 'SFBD'),
	},
	'nfiremachinegun': {
		'SMGS': ('f', 'SMGS'),
		'SMGR': ('i', 'SMGR'),
		'SRCH': ('f', 'SRCH'),
		'BGBR': ('i', 'BGBR'),
		'SDMG': ('f', 'SDMG'),
		'SMGE': ('f', 'SMGE'),
		'SDMT': ('s', 'SDMT'),
		'SBRP': ('ifii', 'SBRP'),
		'SSDT': ('f', 'SSDT'),
		'EDBR': ('v', 'EDBR'),
	},
	'nfiremissile': {
		'SSDI': ('iif', 'SSDI'),
		'DWPN': ('v', 'DWPN'),
		'AWPN': ('iif', 'AWPN'),
		'SVOR': ('iii', 'SVOR'),
		'SSSP': ('i', 'SSSP'),
		'SNUM': ('i', 'SNUM'),
		'SWPP': ('s', 'SWPP'),
		'SSPR': ('i', 'SSPR'),
		'SSTD': ('f', 'SSTD'),
	},
	'nflak': {
		'SRAD': ('f', 'SRAD'),
		'SVMG': ('b', 'SVMG'),
		'SEGY': ('i', 'SEGY'),
		'SRAC': ('f', 'SRAC'),
		'SVGR': ('b', 'SVGR'),
		'SACO': ('f', 'SACO'),
		'SINS': ('b', 'SINS'),
		'SIQS': ('b', 'SIQS'),
		'SUEP': ('b', 'SUEP'),
		'SLFT': ('i', 'SLFT'),
		'SMUA': ('f', 'SMUA'),
		'SVCL': ('s', 'SVCL'),
		'ENEM': ('b', 'ENEM'),
		'SSBA': ('b', 'SSBA'),
		'SMSA': ('f', 'SMSA'),
		'ASTC': ('s', 'ASTC'),
		'SDIR': ('iii', 'set_direction'),
		'SXEY': ('f', 'SXEY'),
		'CCML': ('v', 'CCML'),
		'SRMV': ('b', 'SRMV'),
		'SAUD': ('i', 'SAUD'),
		'SPSD': ('b', 'SPSD'),
		'SSPD': ('iii', 'SSPD'),
		'SFCA': ('b', 'SFCA'),
		'SMAS': ('f', 'SMAS'),
		'SAFM': ('b', 'SAFM'),
		'SQSA': ('b', 'SQSA'),
		'SAUE': ('i', 'SAUE'),
		'SPOP': ('i', 'SPOP'),
		'CSTC': ('v', 'CSTC'),
		'SPOS': ('iii', 'set_position'),
		'SMDA': ('i', 'SMDA'),
		'SAFU': ('b', 'SAFU'),
		'SMCG': ('i', 'SMCG'),
		'SVBL': ('b', 'SVBL'),
		'SISG': ('b', 'SISG'),
		'SCTM': ('i', 'SCTM'),
		'SUTR': ('s', 'SUTR'),
		'STHC': ('b', 'STHC'),
		'SARM': ('si', 'SARM'),
		'SCPP': ('i', 'SCPP'),
		'M_SH': ('b', 'M_SH'),
		'SSTK': ('s', 'SSTK'),
		'SRTI': ('f', 'SRTI'),
		'SBSV': ('iif', 'SBSV'),
		'SCRG': ('i', 'SCRG'),
		'SSTB': ('i', 'SSTB'),
		'SLPP': ('i', 'SLPP'),
		'STHR': ('b', 'STHR'),
		'SSTD': ('f', 'SSTD'),
	},
	'nflakengine2': {
		'SMVR': ('f', 'SMVR'),
		'SUPR': ('b', 'SUPR'),
		'SLAT': ('f', 'SLAT'),
		'SVRT': ('f', 'SVRT'),
		'SHRT': ('f', 'SHRT'),
		'SGRF': ('f', 'SGRF'),
		'SMHR': ('f', 'SMHR'),
		'SCFF': ('b', 'SCFF'),
	},
	'nflakmoving': {
		'SAMV': ('b', 'SAMV'),
		'SART': ('b', 'SART'),
	},
	'nfognode': {
		'SMOD': ('s', 'SMOD'),
		'SCOL': ('ffff', 'SCOL'),
		'SDNS': ('f', 'SDNS'),
		'SRNG': ('if', 'SRNG'),
	},
	'nfreesteer': {
		'SXST': ('f', 'SXST'),
		'SXRT': ('f', 'SXRT'),
		'SXSP': ('f', 'SXSP'),
		'SXLF': ('f', 'SXLF'),
		'STRO': ('f', 'STRO'),
		'SXRO': ('f', 'SXRO'),
		'SXLT': ('f', 'SXLT'),
	},
	'ngarage': {
		'SRAD': ('f', 'SRAD'),
		'SEGY': ('i', 'SEGY'),
		'SRAC': ('i', 'SRAC'),
		'SACO': ('i', 'SACO'),
		'SINS': ('b', 'SINS'),
		'SIQS': ('b', 'SIQS'),
		'SUEP': ('b', 'SUEP'),
		'ENEM': ('b', 'ENEM'),
		'SVCL': ('s', 'SVCL'),
		'SLFT': ('i', 'SLFT'),
		'SDIR': ('iii', 'set_direction'),
		'SXEY': ('f', 'SXEY'),
		'CCML': ('v', 'CCML'),
		'SAUE': ('f', 'SAUE'),
		'SAUD': ('i', 'SAUD'),
		'SPSD': ('b', 'SPSD'),
		'SSPD': ('iii', 'SSPD'),
		'SFCA': ('b', 'SFCA'),
		'SMAS': ('f', 'SMAS'),
		'SAFM': ('b', 'SAFM'),
		'SQSA': ('b', 'SQSA'),
		'SRMV': ('b', 'SRMV'),
		'SPOP': ('i', 'SPOP'),
		'SPOS': ('iii', 'set_position'),
		'SHMR': ('f', 'SHMR'),
		'SSTB': ('i', 'SSTB'),
		'SBDC': ('s', 'SBDC'),
		'SSMD': ('b', 'SSMD'),
		'SAFU': ('b', 'SAFU'),
		'SHMC': ('iii', 'SHMC'),
		'SMCG': ('i', 'SMCG'),
		'SHMA': ('f', 'SHMA'),
		'SAPN': ('s', 'SAPN'),
		'SVBL': ('b', 'SVBL'),
		'SUTR': ('s', 'SUTR'),
		'SCTM': ('i', 'SCTM'),
		'STHC': ('b', 'STHC'),
		'SARM': ('si', 'SARM'),
		'M_SH': ('b', 'M_SH'),
		'SUTE': ('s', 'SUTE'),
		'SRTI': ('i', 'SRTI'),
		'SCRG': ('i', 'SCRG'),
		'SPCT': ('ii', 'SPCT'),
		'SRPN': ('s', 'SRPN'),
		'STHR': ('b', 'STHR'),
		'SAPP': ('ifi', 'SAPP'),
		'SFBD': ('b', 'SFBD'),
	},
	'ngrassrender': {
		'SMSH': ('s', 'SMSH'),
		'SRPT': ('s', 'SRPT'),
		'SSZE': ('f', 'SSZE'),
		'SCHN': ('s', 'SCHN'),
		'SWST': ('i', 'SWST'),
		'SWDR': ('i', 'SWDR'),
		'SSCL': ('f', 'SSCL'),
	},
	'nheal': {
		'SXPE': ('f', 'SXPE'),
		'SSDM': ('b', 'SSDM'),
		'SXPR': ('f', 'SXPR'),
	},
	'nhouse': {
		'SRAD': ('i', 'SRAD'),
		'SEGY': ('i', 'SEGY'),
		'SRAC': ('i', 'SRAC'),
		'SACO': ('i', 'SACO'),
		'SINS': ('b', 'SINS'),
		'SIQS': ('b', 'SIQS'),
		'SUEP': ('b', 'SUEP'),
		'ENEM': ('b', 'ENEM'),
		'SVCL': ('s', 'SVCL'),
		'SLFT': ('i', 'SLFT'),
		'SDIR': ('iii', 'set_direction'),
		'SXEY': ('i', 'SXEY'),
		'CCML': ('v', 'CCML'),
		'SAUE': ('i', 'SAUE'),
		'SAUD': ('i', 'SAUD'),
		'SPSD': ('b', 'SPSD'),
		'SSPD': ('iii', 'SSPD'),
		'SFCA': ('b', 'SFCA'),
		'SMAS': ('f', 'SMAS'),
		'SAFM': ('b', 'SAFM'),
		'SQSA': ('b', 'SQSA'),
		'SRMV': ('b', 'SRMV'),
		'SPOP': ('i', 'SPOP'),
		'SPOS': ('iii', 'set_position'),
		'SHMR': ('f', 'SHMR'),
		'SBDC': ('s', 'SBDC'),
		'SSMD': ('b', 'SSMD'),
		'SAFU': ('b', 'SAFU'),
		'SHMC': ('iii', 'SHMC'),
		'SMCG': ('i', 'SMCG'),
		'SHMA': ('f', 'SHMA'),
		'SVBL': ('b', 'SVBL'),
		'SUTR': ('s', 'SUTR'),
		'SCTM': ('i', 'SCTM'),
		'STHC': ('b', 'STHC'),
		'SARM': ('si', 'SARM'),
		'M_SH': ('b', 'M_SH'),
		'SUTE': ('s', 'SUTE'),
		'SRTI': ('i', 'SRTI'),
		'SCRG': ('i', 'SCRG'),
		'SSTB': ('i', 'SSTB'),
		'STHR': ('b', 'STHR'),
	},
	'nhypermixer2': {
		'ECNC': ('v', 'ECNC'),
		'BCNC': ('i', 'BCNC'),
		'SCNC': ('issss', 'SCNC'),
	},
	'nipolapproachgarage': {
		'SIPD': ('f', 'SIPD'),
		'SDID': ('b', 'SDID'),
		'SDIP': ('b', 'SDIP'),
	},
	'nislanddrive': {
		'SRAD': ('f', 'SRAD'),
		'SEGY': ('i', 'SEGY'),
		'SRAC': ('i', 'SRAC'),
		'SACO': ('i', 'SACO'),
		'SINS': ('b', 'SINS'),
		'SIQS': ('b', 'SIQS'),
		'SUEP': ('b', 'SUEP'),
		'ENEM': ('b', 'ENEM'),
		'SVCL': ('s', 'SVCL'),
		'SLFT': ('i', 'SLFT'),
		'SDIR': ('iii', 'set_direction'),
		'SXEY': ('f', 'SXEY'),
		'CCML': ('v', 'CCML'),
		'SAUE': ('f', 'SAUE'),
		'SAUD': ('i', 'SAUD'),
		'SPSD': ('b', 'SPSD'),
		'SSPD': ('iii', 'SSPD'),
		'SFCA': ('b', 'SFCA'),
		'SMAS': ('f', 'SMAS'),
		'SAFM': ('b', 'SAFM'),
		'SQSA': ('b', 'SQSA'),
		'SRMV': ('b', 'SRMV'),
		'SPOP': ('i', 'SPOP'),
		'SPOS': ('iii', 'set_position'),
		'SHMR': ('f', 'SHMR'),
		'SBDC': ('s', 'SBDC'),
		'SSMD': ('b', 'SSMD'),
		'SAFU': ('b', 'SAFU'),
		'SHMC': ('iii', 'SHMC'),
		'SMCG': ('i', 'SMCG'),
		'SHMA': ('f', 'SHMA'),
		'SVBL': ('b', 'SVBL'),
		'SUTR': ('s', 'SUTR'),
		'SCTM': ('i', 'SCTM'),
		'STHC': ('b', 'STHC'),
		'SARM': ('sf', 'SARM'),
		'M_SH': ('b', 'M_SH'),
		'SUTE': ('s', 'SUTE'),
		'SRTI': ('i', 'SRTI'),
		'SCRG': ('i', 'SCRG'),
		'SSTB': ('i', 'SSTB'),
		'STHR': ('b', 'STHR'),
	},
	'njoint2': {
		'TXYZ': ('fii', 'TXYZ'),
		'OQXZ': ('fiii', 'OQXZ'),
		'QXYZ': ('fiii', 'QXYZ'),
		'OTXZ': ('fii', 'OTXZ'),
	},
	'nleafrender': {
		'SRPT': ('s', 'SRPT'),
		'SMSN': ('s', 'SMSN'),
		'SWST': ('i', 'SWST'),
		'SCHN': ('s', 'SCHN'),
		'SSIZ': ('f', 'SSIZ'),
		'SWDR': ('i', 'SWDR'),
		'SSCL': ('f', 'SSCL'),
	},
	'nlenseflare': {
		'SFPA': ('if', 'SFPA'),
		'SBLC': ('iiii', 'SBLC'),
		'SFS_': ('if', 'SFS_'),
		'BFLR': ('i', 'BFLR'),
		'EFLR': ('v', 'EFLR'),
		'SFCA': ('iffii', 'SFCA'),
	},
	'nlightnode': {
		'SCLR': ('iiii', 'SCLR'),
		'SSPT': ('fi', 'SSPT'),
		'SCSH': ('b', 'SCSH'),
		'SATT': ('iif', 'SATT'),
		'STYP': ('s', 'STYP'),
	},
	'nlistenernode': {
		'SVCH': ('s', 'SVCH'),
		'SRLF': ('f', 'SRLF'),
		'SVCP': ('f', 'SVCP'),
		'SDPF': ('f', 'SDPF'),
	},
	'nmaennel': {
		'SRAD': ('f', 'SRAD'),
		'SVMG': ('b', 'SVMG'),
		'SEGY': ('i', 'SEGY'),
		'STAS': ('b', 'STAS'),
		'SRAC': ('f', 'SRAC'),
		'SVGR': ('b', 'SVGR'),
		'SACO': ('f', 'SACO'),
		'SPVH': ('b', 'SPVH'),
		'SINS': ('b', 'SINS'),
		'SIQS': ('b', 'SIQS'),
		'SUEP': ('b', 'SUEP'),
		'SBCH': ('i', 'SBCH'),
		'ENEM': ('b', 'ENEM'),
		'STIO': ('f', 'STIO'),
		'SVCL': ('s', 'SVCL'),
		'SLFT': ('i', 'SLFT'),
		'CCML': ('v', 'CCML'),
		'SDIR': ('iii', 'set_direction'),
		'SXEY': ('f', 'SXEY'),
		'SCFL': ('b', 'SCFL'),
		'SSBA': ('b', 'SSBA'),
		'RMNO': ('b', 'RMNO'),
		'SAUD': ('i', 'SAUD'),
		'SPSD': ('b', 'SPSD'),
		'STSB': ('fff', 'STSB'),
		'SSPD': ('iii', 'SSPD'),
		'SFCA': ('b', 'SFCA'),
		'SMAS': ('f', 'SMAS'),
		'SAFM': ('b', 'SAFM'),
		'SQSA': ('b', 'SQSA'),
		'SRMV': ('b', 'SRMV'),
		'SQSC': ('s', 'SQSC'),
		'SPOP': ('i', 'SPOP'),
		'CSTC': ('v', 'CSTC'),
		'SPOS': ('iii', 'set_position'),
		'SWOF': ('f', 'SWOF'),
		'SPBL': ('b', 'SPBL'),
		'SMAF': ('i', 'SMAF'),
		'SAUE': ('i', 'SAUE'),
		'SAFU': ('b', 'SAFU'),
		'SMCG': ('i', 'SMCG'),
		'SARM': ('si', 'SARM'),
		'SXBC': ('i', 'SXBC'),
		'SVBL': ('b', 'SVBL'),
		'SISG': ('b', 'SISG'),
		'SCTM': ('i', 'SCTM'),
		'SUTR': ('s', 'SUTR'),
		'STHC': ('b', 'STHC'),
		'SNAC': ('s', 'SNAC'),
		'SCPP': ('i', 'SCPP'),
		'M_SH': ('b', 'M_SH'),
		'SSTK': ('s', 'SSTK'),
		'SRTI': ('f', 'SRTI'),
		'SCRG': ('i', 'SCRG'),
		'SSTB': ('i', 'SSTB'),
		'SLPP': ('i', 'SLPP'),
		'STHR': ('b', 'STHR'),
		'SATL': ('is', 'SATL'),
		'SSTD': ('i', 'SSTD'),
	},
	'nmaennelengine3': {
		'SDTM': ('f', 'SDTM'),
		'SMRL': ('f', 'SMRL'),
		'SXSP': ('f', 'SXSP'),
		'SMPI': ('f', 'SMPI'),
		'SBOT': ('f', 'SBOT'),
		'SISP': ('f', 'SISP'),
		'SYAT': ('f', 'SYAT'),
		'SMPT': ('f', 'SMPT'),
		'SXYR': ('f', 'SXYR'),
		'SMRT': ('f', 'SMRT'),
		'SATM': ('f', 'SATM'),
	},
	'nmaennelwalk2': {
		'SMWA': ('f', 'SMWA'),
		'SSKS': ('f', 'SSKS'),
		'SUPR': ('b', 'SUPR'),
		'SLAT': ('f', 'SLAT'),
		'SCRT': ('i', 'SCRT'),
		'SGRF': ('f', 'SGRF'),
		'SMXS': ('f', 'SMXS'),
		'SMXB': ('f', 'SMXB'),
		'SCVR': ('f', 'SCVR'),
		'SCFF': ('b', 'SCFF'),
	},
	'nmeshipol': {
		'SUV2': ('b', 'SUV2'),
		'SUV3': ('b', 'SUV3'),
		'SUV0': ('b', 'SUV0'),
		'SRPT': ('s', 'SRPT'),
		'SKEY': ('iis', 'SKEY'),
		'EKEY': ('v', 'EKEY'),
		'SUV1': ('b', 'SUV1'),
		'SUCD': ('b', 'SUCD'),
		'SUNM': ('b', 'SUNM'),
		'SCHN': ('s', 'SCHN'),
		'SRDO': ('b', 'SRDO'),
		'BKEY': ('i', 'BKEY'),
		'SUCL': ('b', 'SUCL'),
		'SSCL': ('f', 'SSCL'),
	},
	'nmeshmixer': {
		'SUV2': ('b', 'SUV2'),
		'SUV3': ('b', 'SUV3'),
		'SUV0': ('b', 'SUV0'),
		'SUV1': ('b', 'SUV1'),
		'SRDO': ('b', 'SRDO'),
		'SNRM': ('b', 'SNRM'),
		'SUCD': ('b', 'SUCD'),
		'SUNM': ('b', 'SUNM'),
		'SUCL': ('b', 'SUCL'),
	},
	'nmeshsway': {
		'SRPT': ('s', 'SRPT'),
		'SRDO': ('b', 'SRDO'),
		'SWDD': ('i', 'SWDD'),
		'SFLX': ('f', 'SFLX'),
		'SMND': ('s', 'SMND'),
		'SCHN': ('s', 'SCHN'),
		'SWDS': ('i', 'SWDS'),
		'SSCL': ('f', 'SSCL'),
	},
	'nmgrender': {
		'SRPT': ('s', 'SRPT'),
		'STRR': ('f', 'STRR'),
		'SSPC': ('fffi', 'SSPC'),
		'SCHN': ('s', 'SCHN'),
		'SSSP': ('f', 'SSSP'),
		'SGLR': ('i', 'SGLR'),
		'STRL': ('f', 'STRL'),
		'STRC': ('fffi', 'STRC'),
		'SSPT': ('f', 'SSPT'),
		'SSPS': ('f', 'SSPS'),
		'SSCL': ('f', 'SSCL'),
	},
	'nmissile': {
		'SRAD': ('f', 'SRAD'),
		'SEGY': ('i', 'SEGY'),
		'SRAC': ('f', 'SRAC'),
		'SACO': ('i', 'SACO'),
		'SINS': ('b', 'SINS'),
		'SIQS': ('b', 'SIQS'),
		'SUEP': ('b', 'SUEP'),
		'ENEM': ('b', 'ENEM'),
		'SVCL': ('s', 'SVCL'),
		'SLFT': ('i', 'SLFT'),
		'SSBA': ('b', 'SSBA'),
		'SDIR': ('iii', 'set_direction'),
		'SXEY': ('f', 'SXEY'),
		'CCML': ('v', 'CCML'),
		'SRMV': ('b', 'SRMV'),
		'SAUD': ('i', 'SAUD'),
		'SPSD': ('b', 'SPSD'),
		'SSPD': ('iii', 'SSPD'),
		'SFCA': ('b', 'SFCA'),
		'SMAS': ('f', 'SMAS'),
		'SAFM': ('b', 'SAFM'),
		'SQSA': ('b', 'SQSA'),
		'SAUE': ('i', 'SAUE'),
		'SPOP': ('i', 'SPOP'),
		'CSTC': ('v', 'CSTC'),
		'SPOS': ('iii', 'set_position'),
		'SAFU': ('b', 'SAFU'),
		'SMCG': ('i', 'SMCG'),
		'SVBL': ('b', 'SVBL'),
		'SUTR': ('s', 'SUTR'),
		'SCTM': ('i', 'SCTM'),
		'STHC': ('b', 'STHC'),
		'SARM': ('si', 'SARM'),
		'SCPP': ('i', 'SCPP'),
		'M_SH': ('b', 'M_SH'),
		'SSTK': ('s', 'SSTK'),
		'SRTI': ('f', 'SRTI'),
		'SCRG': ('i', 'SCRG'),
		'SSTB': ('f', 'SSTB'),
		'SLPP': ('i', 'SLPP'),
		'SGDD': ('b', 'SGDD'),
		'STHR': ('b', 'STHR'),
		'SSTD': ('i', 'SSTD'),
	},
	'nmissilecollcheck': {
		'SCCL': ('s', 'SCCL'),
	},
	'nmissileengine2': {
		'SCFF': ('b', 'SCFF'),
		'SUPR': ('b', 'SUPR'),
		'STNT': ('i', 'STNT'),
		'SLAT': ('f', 'SLAT'),
		'SGRF': ('i', 'SGRF'),
		'SMSP': ('i', 'SMSP'),
		'SSPT': ('f', 'SSPT'),
		'SMST': ('f', 'SMST'),
		'STRD': ('i', 'STRD'),
	},
	'nmixer': {
		'BSRC': ('i', 'BSRC'),
		'SSRC': ('iss', 'SSRC'),
		'BCNC': ('i', 'BCNC'),
		'SCNC': ('iss', 'SCNC'),
		'SNRM': ('b', 'SNRM'),
		'ESRC': ('v', 'ESRC'),
		'ECNC': ('v', 'ECNC'),
	},
	'nmnlcollhandle2': {
		'SBNC': ('b', 'SBNC'),
		'SALL': ('b', 'SALL'),
		'SDMG': ('b', 'SDMG'),
		'ADCC': ('s', 'ADCC'),
	},
	'nmodartefact': {
		'SRAD': ('i', 'SRAD'),
		'SMDM': ('i', 'SMDM'),
		'SMDN': ('i', 'SMDN'),
		'SEGY': ('i', 'SEGY'),
		'SRAC': ('i', 'SRAC'),
		'SACO': ('i', 'SACO'),
		'SINS': ('b', 'SINS'),
		'SIQS': ('b', 'SIQS'),
		'SUEP': ('b', 'SUEP'),
		'ENEM': ('b', 'ENEM'),
		'SMDP': ('s', 'SMDP'),
		'SVCL': ('s', 'SVCL'),
		'SLFT': ('i', 'SLFT'),
		'SDIR': ('iii', 'set_direction'),
		'SXEY': ('i', 'SXEY'),
		'CCML': ('v', 'CCML'),
		'SRMV': ('b', 'SRMV'),
		'SAUD': ('i', 'SAUD'),
		'SPSD': ('b', 'SPSD'),
		'SSPD': ('iii', 'SSPD'),
		'SFCA': ('b', 'SFCA'),
		'SMAS': ('i', 'SMAS'),
		'SAFM': ('b', 'SAFM'),
		'SQSA': ('b', 'SQSA'),
		'SAUE': ('i', 'SAUE'),
		'SPOP': ('i', 'SPOP'),
		'SPOS': ('iii', 'set_position'),
		'SAFU': ('b', 'SAFU'),
		'SMCG': ('i', 'SMCG'),
		'SVBL': ('b', 'SVBL'),
		'SUTR': ('s', 'SUTR'),
		'SCTM': ('i', 'SCTM'),
		'STHC': ('b', 'STHC'),
		'M_SH': ('b', 'M_SH'),
		'SRTI': ('i', 'SRTI'),
		'SCRG': ('i', 'SCRG'),
		'SSTB': ('i', 'SSTB'),
		'STHR': ('b', 'STHR'),
	},
	'nmoving': {
		'SAMV': ('b', 'SAMV'),
		'SART': ('b', 'SART'),
	},
	'nnavpoint': {
		'SRAD': ('i', 'SRAD'),
		'SEGY': ('i', 'SEGY'),
		'SRAC': ('i', 'SRAC'),
		'SACO': ('i', 'SACO'),
		'SINS': ('b', 'SINS'),
		'SIQS': ('b', 'SIQS'),
		'DSBL': ('v', 'DSBL'),
		'SUEP': ('b', 'SUEP'),
		'ENEM': ('b', 'ENEM'),
		'SVCL': ('s', 'SVCL'),
		'SLFT': ('i', 'SLFT'),
		'SDIR': ('iii', 'set_direction'),
		'SXEY': ('i', 'SXEY'),
		'CCML': ('v', 'CCML'),
		'SRMV': ('b', 'SRMV'),
		'SAUD': ('i', 'SAUD'),
		'SPSD': ('b', 'SPSD'),
		'SSPD': ('iii', 'SSPD'),
		'SFCA': ('b', 'SFCA'),
		'SMAS': ('i', 'SMAS'),
		'SAFM': ('b', 'SAFM'),
		'SQSA': ('b', 'SQSA'),
		'SAUE': ('i', 'SAUE'),
		'SPOP': ('i', 'SPOP'),
		'SPOS': ('iii', 'set_position'),
		'SAFU': ('b', 'SAFU'),
		'SMCG': ('i', 'SMCG'),
		'SVBL': ('b', 'SVBL'),
		'SUTR': ('s', 'SUTR'),
		'SCTM': ('i', 'SCTM'),
		'STHC': ('b', 'STHC'),
		'STVZ': ('s', 'STVZ'),
		'M_SH': ('b', 'M_SH'),
		'SRTI': ('i', 'SRTI'),
		'SCRG': ('i', 'SCRG'),
		'SSTB': ('i', 'SSTB'),
		'STHR': ('b', 'STHR'),
	},
	'nnavpointsteer': {
		'SXST': ('f', 'SXST'),
		'SXRT': ('f', 'SXRT'),
		'SXSP': ('f', 'SXSP'),
		'SXLF': ('f', 'SXLF'),
		'STRO': ('f', 'STRO'),
		'SXRO': ('f', 'SXRO'),
		'SXLT': ('f', 'SXLT'),
	},
	'nore': {
		'SRAD': ('f', 'SRAD'),
		'SEGY': ('i', 'SEGY'),
		'SRAC': ('i', 'SRAC'),
		'SOQU': ('f', 'SOQU'),
		'SACO': ('i', 'SACO'),
		'SINS': ('b', 'SINS'),
		'SIQS': ('b', 'SIQS'),
		'SUEP': ('b', 'SUEP'),
		'ENEM': ('b', 'ENEM'),
		'SVCL': ('s', 'SVCL'),
		'SLFT': ('i', 'SLFT'),
		'SDIR': ('iii', 'set_direction'),
		'SXEY': ('i', 'SXEY'),
		'CCML': ('v', 'CCML'),
		'SRMV': ('b', 'SRMV'),
		'SAUD': ('i', 'SAUD'),
		'SPSD': ('b', 'SPSD'),
		'SSPD': ('iii', 'SSPD'),
		'SFCA': ('b', 'SFCA'),
		'SMAS': ('f', 'SMAS'),
		'SAFM': ('b', 'SAFM'),
		'SQSA': ('b', 'SQSA'),
		'SAUE': ('i', 'SAUE'),
		'SPOP': ('i', 'SPOP'),
		'SPOS': ('iii', 'set_position'),
		'SAFU': ('b', 'SAFU'),
		'SMCG': ('i', 'SMCG'),
		'SVBL': ('b', 'SVBL'),
		'SUTR': ('s', 'SUTR'),
		'SCTM': ('i', 'SCTM'),
		'STHC': ('b', 'STHC'),
		'SARM': ('sf', 'SARM'),
		'M_SH': ('b', 'M_SH'),
		'SRTI': ('i', 'SRTI'),
		'SCRG': ('i', 'SCRG'),
		'SSTB': ('i', 'SSTB'),
		'STHR': ('b', 'STHR'),
	},
	'npawnshop': {
		'SRAD': ('f', 'SRAD'),
		'SEGY': ('i', 'SEGY'),
		'SRAC': ('i', 'SRAC'),
		'SACO': ('i', 'SACO'),
		'SINS': ('b', 'SINS'),
		'SIQS': ('b', 'SIQS'),
		'SUEP': ('b', 'SUEP'),
		'ENEM': ('b', 'ENEM'),
		'SVCL': ('s', 'SVCL'),
		'SLFT': ('i', 'SLFT'),
		'SDIR': ('iii', 'set_direction'),
		'SXEY': ('f', 'SXEY'),
		'CCML': ('v', 'CCML'),
		'SAUE': ('f', 'SAUE'),
		'SAUD': ('i', 'SAUD'),
		'SPSD': ('b', 'SPSD'),
		'SSPD': ('iii', 'SSPD'),
		'SFCA': ('b', 'SFCA'),
		'SMAS': ('f', 'SMAS'),
		'SAFM': ('b', 'SAFM'),
		'SQSA': ('b', 'SQSA'),
		'SRMV': ('b', 'SRMV'),
		'SPOP': ('i', 'SPOP'),
		'SPOS': ('iii', 'set_position'),
		'SHMR': ('f', 'SHMR'),
		'SSTB': ('i', 'SSTB'),
		'SBDC': ('s', 'SBDC'),
		'SSMD': ('b', 'SSMD'),
		'SAFU': ('b', 'SAFU'),
		'SHMC': ('iii', 'SHMC'),
		'SMCG': ('i', 'SMCG'),
		'SHMA': ('f', 'SHMA'),
		'SMPD': ('i', 'SMPD'),
		'SVBL': ('b', 'SVBL'),
		'SUTR': ('s', 'SUTR'),
		'SCTM': ('i', 'SCTM'),
		'STHC': ('b', 'STHC'),
		'SARM': ('si', 'SARM'),
		'M_SH': ('b', 'M_SH'),
		'SUTE': ('s', 'SUTE'),
		'SRTI': ('i', 'SRTI'),
		'SCRG': ('i', 'SCRG'),
		'SPCT': ('ii', 'SPCT'),
		'STHR': ('b', 'STHR'),
		'SFBD': ('b', 'SFBD'),
	},
	'nphysics': {
		'IGNB': ('b', 'IGNB'),
		'IGNS': ('b', 'IGNS'),
		'IGNF': ('b', 'IGNF'),
	},
	'nplacehouse': {
		'SLGD': ('b', 'SLGD'),
	},
	'nplacespellaction': {
		'SOWC': ('s', 'SOWC'),
		'SADS': ('i', 'SADS'),
		'SPLM': ('s', 'SPLM'),
		'SSTD': ('f', 'SSTD'),
		'SSPA': ('s', 'SSPA'),
	},
	'npointemitter': {
		'SRPT': ('s', 'SRPT'),
		'SACC': ('iii', 'SACC'),
		'STMS': ('iii', 'STMS'),
		'SSPD': ('i', 'SSPD'),
		'SCHN': ('s', 'SCHN'),
		'SICN': ('i', 'SICN'),
		'SOCN': ('i', 'SOCN'),
		'SFRQ': ('f', 'SFRQ'),
		'SLFT': ('f', 'SLFT'),
		'SSCL': ('f', 'SSCL'),
	},
	'npowersupply': {
		'SPPS': ('f', 'SPPS'),
	},
	'nreplenish': {
		'SRFR': ('f', 'SRFR'),
		'SRCO': ('f', 'SRCO'),
	},
	'nsammler': {
		'SRAD': ('f', 'SRAD'),
		'SVMG': ('b', 'SVMG'),
		'SEGY': ('f', 'SEGY'),
		'SRAC': ('f', 'SRAC'),
		'SVGR': ('b', 'SVGR'),
		'SACO': ('f', 'SACO'),
		'SCCT': ('i', 'SCCT'),
		'SINS': ('b', 'SINS'),
		'SIQS': ('b', 'SIQS'),
		'SUEP': ('b', 'SUEP'),
		'SLFT': ('i', 'SLFT'),
		'SVCL': ('s', 'SVCL'),
		'ENEM': ('b', 'ENEM'),
		'SSBA': ('b', 'SSBA'),
		'ASTC': ('s', 'ASTC'),
		'SDIR': ('iii', 'set_direction'),
		'SXEY': ('f', 'SXEY'),
		'CCML': ('v', 'CCML'),
		'SRMV': ('b', 'SRMV'),
		'SAUD': ('i', 'SAUD'),
		'SPSD': ('b', 'SPSD'),
		'SSPD': ('iii', 'SSPD'),
		'SFCA': ('b', 'SFCA'),
		'SMAS': ('f', 'SMAS'),
		'SAFM': ('b', 'SAFM'),
		'SQSA': ('b', 'SQSA'),
		'SAUE': ('f', 'SAUE'),
		'SPOP': ('i', 'SPOP'),
		'CSTC': ('v', 'CSTC'),
		'SPOS': ('iii', 'set_position'),
		'SMCT': ('f', 'SMCT'),
		'SAFU': ('b', 'SAFU'),
		'SMCG': ('i', 'SMCG'),
		'SVBL': ('b', 'SVBL'),
		'SISG': ('b', 'SISG'),
		'SCTM': ('i', 'SCTM'),
		'SUTR': ('s', 'SUTR'),
		'STHC': ('b', 'STHC'),
		'SARM': ('sf', 'SARM'),
		'SCPP': ('i', 'SCPP'),
		'M_SH': ('b', 'M_SH'),
		'SSTK': ('s', 'SSTK'),
		'SRTI': ('f', 'SRTI'),
		'SCRG': ('i', 'SCRG'),
		'SSTB': ('f', 'SSTB'),
		'SLPP': ('i', 'SLPP'),
		'STHR': ('b', 'STHR'),
		'SSTD': ('f', 'SSTD'),
	},
	'nshadowcontrol': {
		'SCOL': ('iiii', 'SCOL'),
	},
	'nsilo': {
		'SCAP': ('i', 'SCAP'),
	},
	'nsoundnode': {
		'STCH': ('s', 'STCH'),
		'SLOP': ('b', 'SLOP'),
		'SAMB': ('b', 'SAMB'),
		'SVOL': ('i', 'SVOL'),
		'SMMD': ('ff', 'SMMD'),
		'SFIL': ('s', 'SFIL'),
		'SPRI': ('f', 'SPRI'),
		'SFRQ': ('f', 'SFRQ'),
		'SDOP': ('b', 'SDOP'),
	},
	'nspawnpoint': {
		'SRAD': ('i', 'SRAD'),
		'SEGY': ('i', 'SEGY'),
		'SRAC': ('i', 'SRAC'),
		'SACO': ('i', 'SACO'),
		'SINS': ('b', 'SINS'),
		'SIQS': ('b', 'SIQS'),
		'SUEP': ('b', 'SUEP'),
		'ENEM': ('b', 'ENEM'),
		'SVCL': ('s', 'SVCL'),
		'SLFT': ('i', 'SLFT'),
		'SDIR': ('iii', 'set_direction'),
		'SXEY': ('i', 'SXEY'),
		'CCML': ('v', 'CCML'),
		'SAUE': ('i', 'SAUE'),
		'SAUD': ('i', 'SAUD'),
		'SPSD': ('b', 'SPSD'),
		'SSPD': ('iii', 'SSPD'),
		'SFCA': ('b', 'SFCA'),
		'SMAS': ('i', 'SMAS'),
		'SAFM': ('b', 'SAFM'),
		'SQSA': ('b', 'SQSA'),
		'SRMV': ('b', 'SRMV'),
		'SPOP': ('i', 'SPOP'),
		'SPOS': ('iii', 'set_position'),
		'SAFU': ('b', 'SAFU'),
		'SMCG': ('i', 'SMCG'),
		'SVBL': ('b', 'SVBL'),
		'SUTR': ('s', 'SUTR'),
		'SCTM': ('i', 'SCTM'),
		'STHC': ('b', 'STHC'),
		'M_SH': ('b', 'M_SH'),
		'SRTI': ('i', 'SRTI'),
		'SCRG': ('i', 'SCRG'),
		'SSTB': ('i', 'SSTB'),
		'STHR': ('b', 'STHR'),
	},
	'nsquadronwatchtarget': {
		'SRAT': ('b', 'SRAT'),
		'SFTD': ('i', 'SFTD'),
		'SFTA': ('f', 'SFTA'),
	},
	'nstandardmenu': {
		'SMRD': ('f', 'SMRD'),
		'SIDS': ('f', 'SIDS'),
		'SISP': ('f', 'SISP'),
		'STAD': ('f', 'STAD'),
	},
	'nstatewatch': {
		'RTMD': ('i', 'RTMD'),
		'SWAC': ('s', 'SWAC'),
		'AACC': ('s', 'AACC'),
		'STOU': ('i', 'STOU'),
		'DACC': ('v', 'DACC'),
		'DDEC': ('v', 'DDEC'),
		'SCLP': ('s', 'SCLP'),
		'ADEC': ('s', 'ADEC'),
	},
	'nstaticmeshemitter': {
		'SRPT': ('s', 'SRPT'),
		'SACC': ('iii', 'SACC'),
		'SMSN': ('s', 'SMSN'),
		'STMS': ('iii', 'STMS'),
		'SSPD': ('f', 'SSPD'),
		'SCHN': ('s', 'SCHN'),
		'SICN': ('i', 'SICN'),
		'SOCN': ('i', 'SOCN'),
		'SFRQ': ('f', 'SFRQ'),
		'SLFT': ('f', 'SLFT'),
		'SSCL': ('f', 'SSCL'),
	},
	'nstation': {
		'SRAD': ('f', 'SRAD'),
		'SMDN': ('i', 'SMDN'),
		'SEGY': ('i', 'SEGY'),
		'FCBA': ('v', 'FCBA'),
		'SRAC': ('i', 'SRAC'),
		'SSPD': ('iii', 'SSPD'),
		'SSPY': ('ifi', 'SSPY'),
		'SINS': ('b', 'SINS'),
		'ADBS': ('s', 'ADBS'),
		'SIQS': ('b', 'SIQS'),
		'SSPX': ('ifi', 'SSPX'),
		'SUEP': ('b', 'SUEP'),
		'ENEM': ('b', 'ENEM'),
		'SVCL': ('s', 'SVCL'),
		'SLFT': ('i', 'SLFT'),
		'SDIR': ('iii', 'set_direction'),
		'SXEY': ('f', 'SXEY'),
		'CCML': ('v', 'CCML'),
		'SRMV': ('b', 'SRMV'),
		'SAUD': ('i', 'SAUD'),
		'SPSD': ('b', 'SPSD'),
		'SACO': ('i', 'SACO'),
		'SFCA': ('b', 'SFCA'),
		'SMAS': ('f', 'SMAS'),
		'SAFM': ('b', 'SAFM'),
		'SQSA': ('b', 'SQSA'),
		'SAUE': ('i', 'SAUE'),
		'SPOP': ('i', 'SPOP'),
		'SPOS': ('iii', 'set_position'),
		'SCSP': ('iii', 'SCSP'),
		'SAFU': ('b', 'SAFU'),
		'SMCG': ('i', 'SMCG'),
		'MBST': ('iii', 'MBST'),
		'SVBL': ('b', 'SVBL'),
		'SUTR': ('s', 'SUTR'),
		'SCTM': ('i', 'SCTM'),
		'STHC': ('b', 'STHC'),
		'SARM': ('si', 'SARM'),
		'M_SH': ('b', 'M_SH'),
		'SRTI': ('f', 'SRTI'),
		'SCRG': ('i', 'SCRG'),
		'SSTB': ('i', 'SSTB'),
		'SSPZ': ('ifi', 'SSPZ'),
		'STHR': ('b', 'STHR'),
		'RBST': ('iii', 'RBST'),
	},
	'nstationcollhandle2': {
		'SBNC': ('b', 'SBNC'),
		'SDMG': ('b', 'SDMG'),
	},
	'nstationengine3': {
		'SDST': ('f', 'SDST'),
	},
	'nstoragemenu': {
		'SMRD': ('f', 'SMRD'),
		'SIDS': ('f', 'SIDS'),
		'SISP': ('f', 'SISP'),
		'STAD': ('f', 'STAD'),
	},
	'nsubtitle': {
		'SRAD': ('i', 'SRAD'),
		'SEGY': ('i', 'SEGY'),
		'SRAC': ('i', 'SRAC'),
		'SACO': ('i', 'SACO'),
		'SINS': ('b', 'SINS'),
		'SIQS': ('b', 'SIQS'),
		'SUEP': ('b', 'SUEP'),
		'ENEM': ('b', 'ENEM'),
		'SVCL': ('s', 'SVCL'),
		'SLFT': ('i', 'SLFT'),
		'SDIR': ('iii', 'set_direction'),
		'SXEY': ('i', 'SXEY'),
		'CCML': ('v', 'CCML'),
		'SAUE': ('i', 'SAUE'),
		'SAUD': ('i', 'SAUD'),
		'SPSD': ('b', 'SPSD'),
		'SSPD': ('iii', 'SSPD'),
		'SFCA': ('b', 'SFCA'),
		'SMAS': ('i', 'SMAS'),
		'SAFM': ('b', 'SAFM'),
		'SQSA': ('b', 'SQSA'),
		'SRMV': ('b', 'SRMV'),
		'SPOP': ('i', 'SPOP'),
		'SPOS': ('iii', 'set_position'),
		'SAFU': ('b', 'SAFU'),
		'SMCG': ('i', 'SMCG'),
		'SVBL': ('b', 'SVBL'),
		'SUTR': ('s', 'SUTR'),
		'SCTM': ('i', 'SCTM'),
		'STHC': ('b', 'STHC'),
		'M_SH': ('b', 'M_SH'),
		'SRTI': ('i', 'SRTI'),
		'SCRG': ('i', 'SCRG'),
		'SSTB': ('i', 'SSTB'),
		'STHR': ('b', 'STHR'),
	},
	'nsubtitleaudio': {
		'SAUD': ('s', 'SAUD'),
	},
	'nsubtitlevisual': {
		'SVIS': ('s', 'SVIS'),
	},
	'nswimmingengine': {
		'SULS': ('f', 'SULS'),
		'SYAT': ('f', 'SYAT'),
		'SFSP': ('f', 'SFSP'),
		'SXYR': ('f', 'SXYR'),
		'SFST': ('f', 'SFST'),
		'SBKT': ('f', 'SBKT'),
	},
	'nswingengine': {
		'SESW': ('b', 'SESW'),
	},
	'ntestpossess': {
		'SPCC': ('s', 'SPCC'),
	},
	'ntexarraynode': {
		'SGMM': ('ib', 'SGMM'),
		'STXT': ('iss', 'STXT'),
		'SHQL': ('ib', 'SHQL'),
	},
	'nthreshnode': {
		'SCHN': ('s', 'SCHN'),
		'SUPB': ('f', 'SUPB'),
		'SRPT': ('s', 'SRPT'),
		'SLWB': ('i', 'SLWB'),
		'SSCL': ('f', 'SSCL'),
	},
	'ntrademenu': {
		'SMRD': ('f', 'SMRD'),
		'SIDS': ('f', 'SIDS'),
		'SISP': ('f', 'SISP'),
		'STAD': ('f', 'STAD'),
	},
	'ntransformmenu': {
		'SMRD': ('f', 'SMRD'),
		'SIDS': ('f', 'SIDS'),
		'SISP': ('f', 'SISP'),
		'STAD': ('f', 'STAD'),
	},
	'ntriggerobject': {
		'SRAD': ('i', 'SRAD'),
		'SEGY': ('i', 'SEGY'),
		'SRAC': ('i', 'SRAC'),
		'SACO': ('i', 'SACO'),
		'SINS': ('b', 'SINS'),
		'SCCL': ('i', 'SCCL'),
		'SAFM': ('b', 'SAFM'),
		'SIQS': ('b', 'SIQS'),
		'SUEP': ('b', 'SUEP'),
		'SLFT': ('i', 'SLFT'),
		'SVCL': ('s', 'SVCL'),
		'ENEM': ('b', 'ENEM'),
		'SDIR': ('iii', 'set_direction'),
		'SXEY': ('i', 'SXEY'),
		'CCML': ('v', 'CCML'),
		'SRMV': ('b', 'SRMV'),
		'SAUD': ('i', 'SAUD'),
		'SPSD': ('b', 'SPSD'),
		'SSPD': ('iii', 'SSPD'),
		'SFCA': ('b', 'SFCA'),
		'SMAS': ('i', 'SMAS'),
		'SFLT': ('s', 'SFLT'),
		'SQSA': ('b', 'SQSA'),
		'SAUE': ('i', 'SAUE'),
		'SPOP': ('i', 'SPOP'),
		'SPOS': ('iii', 'set_position'),
		'STRD': ('f', 'STRD'),
		'STIM': ('f', 'STIM'),
		'SAFU': ('b', 'SAFU'),
		'SMCG': ('i', 'SMCG'),
		'SVBL': ('b', 'SVBL'),
		'SUTR': ('s', 'SUTR'),
		'SCTM': ('i', 'SCTM'),
		'STHC': ('b', 'STHC'),
		'M_SH': ('b', 'M_SH'),
		'SRTI': ('i', 'SRTI'),
		'SCRG': ('i', 'SCRG'),
		'SSTB': ('i', 'SSTB'),
		'STHR': ('b', 'STHR'),
		'SNMC': ('i', 'SNMC'),
	},
	'nunloadore': {
		'SUPS': ('f', 'SUPS'),
	},
	'nvehicle': {
		'SRAD': ('f', 'SRAD'),
		'SVMG': ('b', 'SVMG'),
		'SEGY': ('i', 'SEGY'),
		'SRAC': ('f', 'SRAC'),
		'SVGR': ('b', 'SVGR'),
		'SACO': ('f', 'SACO'),
		'SINS': ('b', 'SINS'),
		'SIQS': ('b', 'SIQS'),
		'SUEP': ('b', 'SUEP'),
		'SLFT': ('i', 'SLFT'),
		'SVCL': ('s', 'SVCL'),
		'ENEM': ('b', 'ENEM'),
		'SSBA': ('b', 'SSBA'),
		'ASTC': ('s', 'ASTC'),
		'SDIR': ('iii', 'set_direction'),
		'SXEY': ('f', 'SXEY'),
		'CCML': ('v', 'CCML'),
		'SRMV': ('b', 'SRMV'),
		'SAUD': ('i', 'SAUD'),
		'SPSD': ('b', 'SPSD'),
		'SSPD': ('iii', 'SSPD'),
		'SFCA': ('b', 'SFCA'),
		'SMAS': ('f', 'SMAS'),
		'SAFM': ('b', 'SAFM'),
		'SQSA': ('b', 'SQSA'),
		'SAUE': ('i', 'SAUE'),
		'SPOP': ('i', 'SPOP'),
		'CSTC': ('v', 'CSTC'),
		'SPOS': ('iii', 'set_position'),
		'SAFU': ('b', 'SAFU'),
		'SMCG': ('i', 'SMCG'),
		'SVBL': ('b', 'SVBL'),
		'SISG': ('b', 'SISG'),
		'SCTM': ('i', 'SCTM'),
		'SUTR': ('s', 'SUTR'),
		'STHC': ('b', 'STHC'),
		'SARM': ('si', 'SARM'),
		'SCPP': ('i', 'SCPP'),
		'M_SH': ('b', 'M_SH'),
		'SSTK': ('s', 'SSTK'),
		'SRTI': ('f', 'SRTI'),
		'SCRG': ('i', 'SCRG'),
		'SSTB': ('f', 'SSTB'),
		'SLPP': ('i', 'SLPP'),
		'STHR': ('b', 'STHR'),
		'SSTD': ('i', 'SSTD'),
	},
	'nvehicleemitter': {
		'ADDV': ('sf', 'ADDV'),
		'SSPA': ('f', 'SSPA'),
		'STRO': ('b', 'STRO'),
		'STLP': ('b', 'STLP'),
		'SYOS': ('i', 'SYOS'),
		'SEMS': ('f', 'SEMS'),
	},
	'nviewerdata': {
		'SCND': ('s', 'SCND'),
		'SWND': ('s', 'SWND'),
		'SHRC': ('b', 'SHRC'),
		'SNRT': ('s', 'SNRT'),
		'SKPP': ('b', 'SKPP'),
	},
	'nvisnode': {
		'SFAF': ('f', 'SFAF'),
	},
	'nvisual': {
		'SAFN': ('s', 'SAFN'),
		'SVIS': ('s', 'SVIS'),
		'SCHS': ('s', 'SCHS'),
	},
	'nwalkcollhandle2': {
		'SMSH': ('f', 'SMSH'),
		'SJCH': ('f', 'SJCH'),
		'SMWA': ('f', 'SMWA'),
		'ADCC': ('s', 'ADCC'),
		'SJCL': ('f', 'SJCL'),
		'SDMG': ('b', 'SDMG'),
		'SALL': ('b', 'SALL'),
		'SBNC': ('b', 'SBNC'),
	},
	'nwalkovercheck': {
		'SRAD': ('i', 'SRAD'),
		'SCLC': ('s', 'SCLC'),
	},
	'nwalkoverhandle': {
		'SBNC': ('b', 'SBNC'),
		'SDMG': ('b', 'SDMG'),
	},
	'nwatchtarget': {
		'SRAT': ('b', 'SRAT'),
	},
	'nweatherdesc': {
		'SRAD': ('i', 'SRAD'),
		'SEGY': ('i', 'SEGY'),
		'SRAC': ('i', 'SRAC'),
		'SACO': ('i', 'SACO'),
		'SINS': ('b', 'SINS'),
		'SAFM': ('b', 'SAFM'),
		'SIQS': ('b', 'SIQS'),
		'SUEP': ('b', 'SUEP'),
		'SLFT': ('i', 'SLFT'),
		'SVCL': ('s', 'SVCL'),
		'ENEM': ('b', 'ENEM'),
		'SCDP': ('s', 'SCDP'),
		'SDIR': ('iii', 'set_direction'),
		'SXEY': ('i', 'SXEY'),
		'CCML': ('v', 'CCML'),
		'SRMV': ('b', 'SRMV'),
		'SAUD': ('i', 'SAUD'),
		'SPSD': ('b', 'SPSD'),
		'SSPD': ('iii', 'SSPD'),
		'SFCA': ('b', 'SFCA'),
		'SMAS': ('i', 'SMAS'),
		'SDFT': ('b', 'SDFT'),
		'SQSA': ('b', 'SQSA'),
		'SAUE': ('i', 'SAUE'),
		'SPOP': ('i', 'SPOP'),
		'SPOS': ('iii', 'set_position'),
		'SAFU': ('b', 'SAFU'),
		'SMCG': ('i', 'SMCG'),
		'SVBL': ('b', 'SVBL'),
		'SUTR': ('s', 'SUTR'),
		'SCTM': ('i', 'SCTM'),
		'STHC': ('b', 'STHC'),
		'M_SH': ('b', 'M_SH'),
		'SRTI': ('i', 'SRTI'),
		'SAOE': ('i', 'SAOE'),
		'SCRG': ('i', 'SCRG'),
		'SSTB': ('i', 'SSTB'),
		'STHR': ('b', 'STHR'),
	}
}